server:
  servlet:
    context-path: /gxy
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://localhost:3306/springboot
    data-username: root
    data-password: root
  servlet:
    multipart:
      file-size-threshold: 20MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity